work_subdir_name: "operator-test"
work_dir: "/tmp/{{ work_subdir_name }}"
image_protocol: "docker://"
operator_work_dir: "{{ work_dir }}/operator-files"
testing_bin_path: "{{ work_dir }}/bin"
jq_bin_path: "{{ testing_bin_path }}/jq"
yq_bin_path: "{{ testing_bin_path }}/yq"
go_bin_path: "{{ testing_bin_path }}/go/bin/go"
operator_sdk_bin_path: "{{ testing_bin_path }}/operator-sdk"
umoci_bin_path: "{{ testing_bin_path }}/umoci"
opm_bin_path: "{{ testing_bin_path }}/opm"
offline_cataloger_bin_path: "offline-cataloger"
kind_version: v0.9.0
kind_checksum: "sha256:35a640e0ca479192d86a51b6fd31c657403d2cf7338368d62223938771500dc8"
kind_kube_version: v1.19.1
operator_sdk_version: v1.25.0
operator_sdk_checksum: "sha256:35fcbc4d20b98c2d52ae4645254cec18060992530f406ac839e62a984f1a049a"
olm_version: 0.20.0
olm_checksum: "sha256:4e700234a76267a3a6918493af18be624ee44d8bd734ad9cf924d73b0673a7ca"
opm_version: v1.21.0
opm_checksum: "sha256:fa4efe23d2e951c2540f7fe57c58264b69b1d396d5ab54b454c612a69c338514"
yq_version: 2.2.1
yq_checksum: "sha256:54443f0e9796dfb8423a6e33b8175a0f77b8bb0eb55db820ecb84098db2c0ed4"
operator_allnamespaces_support: false
operator_ownnamespace_support: false
operator_singlenamespace_support: true
operator_multinamespace_support: false
run_upstream: false
bundle_registry: quay.io
oc_bin_path: "{{ 'kubectl' if run_upstream else 'oc' }}"
openshift_namespace: test-operators
quay_namespace: operator_testing_community
current_channel: alpha
quay_release: 0.0.1
kubeconfig_path: "{{ ansible_env.HOME }}/.kube/config"
olm_operator_files_path: "/tmp/oper-to-deploy-{{ dir_suffix_part }}"
run_bundle_test: false
operator_bundle_src_dir: "{{ work_dir }}/operators"
operator_dir_name: "{{ operator_dir | basename }}"
test_quay_namespace: operator_testing
operator_suggested_namespace_default: test-operators
pod_start_retries: 90
current_openshift_run: "4.7"
oc_version_max: "4.13"
operator_upgrade_testing_on_openshift_disabled: false
